linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - staticcheck
    - unused
    - gosimple
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    