name: Snyk Security

on:
  push:
    branches: [ main, PR ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # Specify your Go version

    - name: Download Go Modules
      run: go mod download

    - name: Set up Snyk CLI
      uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      with:
        snyk-token: ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Open Source (SCA) Analysis
      run: snyk test --all-projects

    - name: Snyk Code (SAST) Analysis
      run: snyk code test